#! /bin/bash
#
# Test script to run the Groovy script against
#  each file in the SRC directory. Output to
#  files labeled p1o.csv. Directory will be
#  cleaned before running the script.
#################################################

SRCDIR="../../src"
OUTPUTDIR="../work/phase1"
CONVSCRIPT="../../scripts/streamToTab.groovy"

# Make sure we can run it
which groovy >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "You must install Groovy or put it in your path to run these tests."
    exit 1
fi

if [ ! -f ${CONVSCRIPT} ]; then
    echo "Where is ${CONVSCRIPT} ? I can't find it."
    exit 1
fi

if [ -d ${OUTPUTDIR} ]; then
    rm ${OUTPUTDIR}/*
else
    mkdir -p ${OUTPUTDIR}
fi

counter=0

for srcfile in `ls $SRCDIR/*.txt`
do
    targfile="${OUTPUTDIR}/`basename ${srcfile}`_phase1.csv"
    groovy ${CONVSCRIPT} ${srcfile} > ${targfile}
    counter=`expr 1 + $counter` 
done

echo "${counter} files converted to ${OUTPUTDIR}"