#! /bin/bash
#
# Test script to run the Groovy script against
#  each file in the SRC directory. Output to
#  files labeled p1o.csv. Directory will be
#  cleaned before running the script.
#################################################

SRCDIR="../../src"
P1ODIR="phase1-output"
CONVSCRIPT="../../scripts/streamToTab.groovy"

# Make sure we can run it
if [ (which groovy >/dev/null) -ne 0 ]; then
    echo "You must install Groovy or put it in your path to run these tests."
    exit 1
fi

if [ ! -f ${CONVSCRIPT} ]; then
    echo "Where is ${CONVSCRIPT} ? I can't find it."
    exit 1
fi

counter=0

for srcfile in `ls $SRCDIR`
do
    targfile="${P1ODIR}/`basename ${srcfile}`.p1o.csv"
    groovy ${CONVSCRIPT} $srcfile > $targfile
    counter=`expr 1 + $counter` 
done

echo "${counter} files converted to ${P1ODIR}"