#! /bin/bash
#
# Test script to apply Ryan's regex transformations
#  using ex. Input is all-p1o-lines.txt. Output
#  is after-p2.txt. Since ex is editing the file
#  in place, we want to avoid damaging our input
#  file. Call diff at the end so we can see
#  whether we did anything. 
#################################################

SRCFILE="all-p1o-lines.txt"
TARGET="after-p2.txt"
REGEXFILES="set-source-urn.ex"
BACKUPS="backup-results"

if [ ! -d ${BACKUPS} ]; then
   mkdir -p ${BACKUPS}
fi   

if [ -f ${TARGET} ]; then
   backupfile=`date "+${BACKUPS}/${TARGET}.%Y%m%d-%H%M%S"`
   cp -p ${TARGET} ${backupfile}
fi

# Running ex is a destructive process
cp -p ${SRCFILE} ${TARGET}

for regexfile in ${REGEXFILES}
do
    if [ ! -f ${regexfile} ]; then
	echo "No input regex file ${script} found."
	exit 1
    fi

    echo "Applying ${regexfile} to ${TARGET}"
    ex -S ${regexfile} ${TARGET}
    echo "Finished applying ${regexfile}"
done

echo "Finished running all regex files"

