#! /bin/bash
#
# Test script to run the MRTBP script against
#  each file in the phase1 output directory.
#################################################

SRCDIR="../work/phase1"
OUTPUTDIR="../work/phase2"
MRBTPDIR="../../mrbtp"
MRBTPSCRIPT="transform"

#############
# FUNCTIONS #
#############

####################################################
# Return the absolute path for the argument passed #
####################################################

get_absolute_path () {
    ABSPATH=''
    if [ "X$1" = "X" ]; then
	return 1
    fi
    pushd `dirname $1` >/dev/null
    ABSPATH=`pwd`
    popd >/dev/null
    ABSPATH=${ABSPATH}/`basename $1`
}

############################
# MAIN PROGRAM BEGINS HERE #
############################

get_absolute_path "${MRBTPDIR}/${MRBTPSCRIPT}"
EXECFILE=${ABSPATH}

if [ ! -x ${EXECFILE} ]; then
    echo "Where is ${EXECFILE} ?"
    exit 1
fi

if [ -d ${OUTPUTDIR} ]; then
    rm ${OUTPUTDIR}/* 2>/dev/null
else
    mkdir -p ${OUTPUTDIR}
fi

counter=0

for srcfile in `ls $SRCDIR/*.csv`
do
    get_absolute_path "${srcfile}"
    sourcefile=${ABSPATH}
    get_absolute_path "${OUTPUTDIR}/`basename ${sourcefile}`"
    targetfile=${ABSPATH}
    pushd ${MRBTPDIR} > /dev/null
    echo "Running: ${EXECFILE} -o ${targetfile} ${sourcefile}"
    ${EXECFILE} -o ${targetfile} ${sourcefile}
    echo "Finished run"
    popd > /dev/null
    counter=`expr 1 + $counter` 
done

echo "${counter} files converted to ${OUTPUTDIR}"