#! /bin/bash
#
# Test script to run the MRTBP script against
#  each file in the phase1 output directory.
#################################################

SRCDIR="../work/phase1"
OUTPUTDIR="../work/phase2"
MRBTPDIR="../../mrbtp"
MRBTPSCRIPT="transform"

#############
# FUNCTIONS #
#############

####################################################
# Return the absolute path for the argument passed #
####################################################

get_absolute_path () {
    startpath=$1
    if [ "X$1" = "X" ]; then
	return ""
    fi

    pushd `dirname ${startpath}`
    absolute_dir=`pwd`
    popd
    return "${absolute_dir}/`basename ${startpath}`"
}

############################
# MAIN PROGRAM BEGINS HERE #
############################

EXECFILE="${MRBTPDIR}/${MRBTPSCRIPT}"

if [ ! -x ${EXECFILE} ]; then
    echo "Where is ${EXECFILE} ?"
    exit 1
fi

if [ -d ${OUTPUTDIR} ]; then
    rm ${OUTPUTDIR}/*
else
    mkdir -p ${OUTPUTDIR}
fi

counter=0

for srcfile in `ls $SRCDIR/*.csv`
do
    targfile=`echo ${srcfile} | sed 's/phase1/phase2/'`
    targfile=`get_absolute_path ${OUTPUTDIR}/$targfile`
    sourcefile=`get_absolute_path $srcfile`
    pushd ${MRBTPDIR}
    ${MRBTPSCRIPT} -o ${targfile} ${sourcefile}
    popd
    counter=`expr 1 + $counter` 
done

echo "${counter} files converted to ${OUTPUTDIR}"